apiVersion: asset.sap/v1
kind: Asset
type: agent

metadata:
  name: mass-balance-orchestrator-agent
  version: 1.0.0

container:
  buildPath: .
  port: 5000

provides:
  apis:
    - name: mass-balance-orchestrator-agent
      kind: a2a
      ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.mass-balance-orchestrator-agent:v1

requires:
  - name: sap-s4-material-stock-mcp-server
    kind: mcp-server
    ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.sap-s4-material-stock-mcp-server:v1
  - name: sap-s4-material-document-mcp-server
    kind: mcp-server
    ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.sap-s4-material-document-mcp-server:v1
  - name: sap-s4-physical-inventory-mcp-server
    kind: mcp-server
    ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.sap-s4-physical-inventory-mcp-server:v1
  - name: sap-s4-stock-transport-order-mcp-server
    kind: mcp-server
    ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.sap-s4-stock-transport-order-mcp-server:v1
  - name: sap-s4-proc-order-confirmation-mcp-server
    kind: mcp-server
    ordId: customer.build:apiResource:mass-balance-reconciliation-a37df.sap-s4-proc-order-confirmation-mcp-server:v1
